# Onkyo component services.yaml entry

select_hdmi_output:
  description: Selects the HDMI output of an Onkyo/Pioneer Network Receiver
  fields:
    entity_id:
      description: Name of the Onkyo entity to set
      example: "media_player.onkyo"
    hdmi_output:
      description: The HDMI output to select (no/analog/yes/out/out-sub/sub/hdbaset/both/up)
      example: "out-sub"
